#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Wed Jan 06 11:21:28 2010

import wx

# begin wxGlade: extracode
import wx.html as html
# end wxGlade



class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = wx.CAPTION|wx.CLOSE_BOX|wx.MINIMIZE_BOX|wx.MAXIMIZE|wx.MAXIMIZE_BOX|wx.SYSTEM_MENU|wx.RESIZE_BORDER|wx.TAB_TRAVERSAL|wx.CLIP_CHILDREN
        wx.Frame.__init__(self, *args, **kwds)
        self.statusbar = self.CreateStatusBar(1, 0)
        
        # Tool Bar
        self.fraBusqueda_toolbar = wx.ToolBar(self, -1)
        self.SetToolBar(self.fraBusqueda_toolbar)
        self.fraBusqueda_toolbar.AddLabelTool(1, "&Recargar", wx.Bitmap("icons\\view-refresh.png", wx.BITMAP_TYPE_ANY), wx.NullBitmap, wx.ITEM_NORMAL, "Recargar", "")
        self.fraBusqueda_toolbar.AddLabelTool(2, "&Anterior", wx.Bitmap("icons\\IrPrevio.png", wx.BITMAP_TYPE_ANY), wx.NullBitmap, wx.ITEM_NORMAL, "Anterior", "")
        self.fraBusqueda_toolbar.AddLabelTool(3, "&Siguiente", wx.Bitmap("icons\\IrSgte.png", wx.BITMAP_TYPE_ANY), wx.NullBitmap, wx.ITEM_NORMAL, "Siguiente", "")
        self.fraBusqueda_toolbar.AddLabelTool(8, "&Copiar", wx.Bitmap("icons\\Copiar.png", wx.BITMAP_TYPE_ANY), wx.NullBitmap, wx.ITEM_NORMAL, "Copiar resultado", "")
        self.fraBusqueda_toolbar.AddLabelTool(7, "&Imprimir", wx.Bitmap("icons\\Imprimir.png", wx.BITMAP_TYPE_ANY), wx.NullBitmap, wx.ITEM_NORMAL, "Imprimir", "")
        self.fraBusqueda_toolbar.AddSeparator()
        self.fraBusqueda_toolbar.AddLabelTool(4, "&Configuracion", wx.Bitmap("icons\\VerConfig.png", wx.BITMAP_TYPE_ANY), wx.NullBitmap, wx.ITEM_NORMAL, "Ver configuracion", "")
        self.fraBusqueda_toolbar.AddLabelTool(6, "&Acerca", wx.Bitmap("icons\\AcercaDe.png", wx.BITMAP_TYPE_ANY), wx.NullBitmap, wx.ITEM_NORMAL, "Acerca de", "")
        # Tool Bar end
        self.txtBusqueda = wx.TextCtrl(self, wx.ID_ANY, "")
        self.btnBusqueda = wx.Button(self, wx.ID_ANY, "&Buscar")
        self.htmlResult = html.HtmlWindow(self, wx.ID_ANY)

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_TOOL, self.DoReiniciar, id=1)
        self.Bind(wx.EVT_TOOL, self.DoAnterior, id=2)
        self.Bind(wx.EVT_TOOL, self.DoSiguiente, id=3)
        self.Bind(wx.EVT_TOOL, self.DoCopiar, id=8)
        self.Bind(wx.EVT_TOOL, self.DoImprimir, id=7)
        self.Bind(wx.EVT_TOOL, self.DoVerConfig, id=4)
        self.Bind(wx.EVT_TOOL, self.DoAcerca, id=6)
        self.Bind(wx.EVT_BUTTON, self.DoCorrer, id=wx.ID_ANY)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle("Buscar Justiciables")
        self.SetSize((772, 458))
        self.statusbar.SetStatusWidths([-1])
        # statusbar fields
        statusbar_fields = ["fraBusqueda_statusbar"]
        for i in range(len(statusbar_fields)):
            self.statusbar.SetStatusText(statusbar_fields[i], i)
        self.fraBusqueda_toolbar.SetToolBitmapSize((48, 48))
        self.fraBusqueda_toolbar.Realize()
        self.txtBusqueda.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.btnBusqueda.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.btnBusqueda.SetDefault()
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        sizer_1 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(self.txtBusqueda, 2, wx.BOTTOM, 4)
        sizer_1.Add(self.btnBusqueda, 0, 0, 0)
        sizer_3.Add(sizer_1, 0, wx.EXPAND, 0)
        sizer_3.Add(self.htmlResult, 2, wx.EXPAND, 2)
        self.SetSizer(sizer_3)
        self.Layout()
        # end wxGlade

    def DoReiniciar(self, event): # wxGlade: MyFrame.<event_handler>
        print "Event handler `DoReiniciar' not implemented!"
        event.Skip()

    def DoAnterior(self, event): # wxGlade: MyFrame.<event_handler>
        print "Event handler `DoAnterior' not implemented!"
        event.Skip()

    def DoSiguiente(self, event): # wxGlade: MyFrame.<event_handler>
        print "Event handler `DoSiguiente' not implemented!"
        event.Skip()

    def DoCopiar(self, event): # wxGlade: MyFrame.<event_handler>
        print "Event handler `DoCopiar' not implemented!"
        event.Skip()

    def DoImprimir(self, event): # wxGlade: MyFrame.<event_handler>
        print "Event handler `DoImprimir' not implemented!"
        event.Skip()

    def DoVerConfig(self, event): # wxGlade: MyFrame.<event_handler>
        print "Event handler `DoVerConfig' not implemented!"
        event.Skip()

    def DoAcerca(self, event): # wxGlade: MyFrame.<event_handler>
        print "Event handler `DoAcerca' not implemented!"
        event.Skip()

    def DoCorrer(self, event): # wxGlade: MyFrame.<event_handler>
        print "Event handler `DoCorrer' not implemented!"
        event.Skip()

# end of class MyFrame


class MyApp(wx.App):
    def OnInit(self):
        wx.InitAllImageHandlers()
        fraBusqueda = MyFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(fraBusqueda)
        fraBusqueda.Show()
        return 1

# end of class MyApp

if __name__ == "__main__":
    Busqueda = MyApp(0)
    Busqueda.MainLoop()
