#!/usr/bin/env python
# -*- coding: iso-8859-15 -*-
# generated by wxGlade 0.6.3 on Tue Jan 19 20:27:10 2010

import wx

# begin wxGlade: extracode
# end wxGlade



class Config(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: Config.__init__
        kwds["style"] = wx.CAPTION|wx.CLOSE_BOX|wx.MINIMIZE_BOX|wx.MAXIMIZE_BOX|wx.SYSTEM_MENU|wx.RESIZE_BORDER|wx.TAB_TRAVERSAL|wx.CLIP_CHILDREN
        wx.Frame.__init__(self, *args, **kwds)
        self.label_1 = wx.StaticText(self, wx.ID_ANY, "Directorio del Lex principal")
        self.txtDirLexMesa = wx.TextCtrl(self, wx.ID_ANY, "", style=wx.TE_READONLY)
        self.btnDirLexMesa = wx.Button(self, 101, "...")
        self.label_2 = wx.StaticText(self, wx.ID_ANY, "Directorio de copia de trabajo del Lex")
        self.txtDirPathLex = wx.TextCtrl(self, wx.ID_ANY, "", style=wx.TE_READONLY)
        self.btnDirPathLex = wx.Button(self, 102, "...")
        self.btnCopiar = wx.Button(self, 4, "&Actualizar copia")
        self.btnGenerar = wx.Button(self, 1, "&Generar indice")
        self.btnAplicar = wx.Button(self, 2, "Aplicar")
        self.btnSalir = wx.Button(self, 3, "&Salir")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.DoDirLexMesa, id=101)
        self.Bind(wx.EVT_BUTTON, self.DoDirPathLex, id=102)
        self.Bind(wx.EVT_BUTTON, self.DoCopiar, id=4)
        self.Bind(wx.EVT_BUTTON, self.DoGenerarIndice, id=1)
        self.Bind(wx.EVT_BUTTON, self.DoAplicar, id=2)
        self.Bind(wx.EVT_BUTTON, self.DoSalir, id=3)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: Config.__set_properties
        self.SetTitle("Administrar y configurar")
        self.SetBackgroundColour(wx.SystemSettings_GetColour(wx.SYS_COLOUR_3DFACE))
        self.btnDirLexMesa.SetMinSize((30, -1))
        self.btnDirPathLex.SetMinSize((30, -1))
        self.btnCopiar.SetToolTipString("Actualizar copia de trabajo del Lex-Doctor")
        self.btnGenerar.SetToolTipString("Regenerar los indices de busqueda")
        self.btnAplicar.SetToolTipString(u"Aplicar los cambios en la configuración")
        self.btnAplicar.SetDefault()
        self.btnSalir.SetToolTipString("Salir del administrador")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: Config.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(self.label_1, 0, wx.ALL, 9)
        sizer_2.Add(self.txtDirLexMesa, 1, 0, 0)
        sizer_2.Add(self.btnDirLexMesa, 0, 0, 0)
        sizer_1.Add(sizer_2, 1, wx.EXPAND, 0)
        sizer_1.Add(self.label_2, 0, wx.ALL, 9)
        sizer_3.Add(self.txtDirPathLex, 1, 0, 0)
        sizer_3.Add(self.btnDirPathLex, 0, 0, 0)
        sizer_1.Add(sizer_3, 1, wx.EXPAND, 0)
        sizer_1.Add((20, 20), 1, wx.EXPAND, 0)
        sizer_4.Add(self.btnCopiar, 0, 0, 0)
        sizer_4.Add(self.btnGenerar, 0, 0, 0)
        sizer_4.Add((20, 20), 1, 0, 0)
        sizer_4.Add(self.btnAplicar, 0, 0, 0)
        sizer_4.Add(self.btnSalir, 0, 0, 0)
        sizer_1.Add(sizer_4, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

    def DoDirLexMesa(self, event): # wxGlade: Config.<event_handler>
        print "Event handler `DoDirLexMesa' not implemented!"
        event.Skip()

    def DoDirPathLex(self, event): # wxGlade: Config.<event_handler>
        print "Event handler `DoDirPathLex' not implemented!"
        event.Skip()

    def DoCopiar(self, event): # wxGlade: Config.<event_handler>
        print "Event handler `DoCopiar' not implemented!"
        event.Skip()

    def DoGenerarIndice(self, event): # wxGlade: Config.<event_handler>
        print "Event handler `DoGenerarIndice' not implemented!"
        event.Skip()

    def DoAplicar(self, event): # wxGlade: Config.<event_handler>
        print "Event handler `DoAplicar' not implemented!"
        event.Skip()

    def DoSalir(self, event): # wxGlade: Config.<event_handler>
        print "Event handler `DoSalir' not implemented!"
        event.Skip()

# end of class Config


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_1 = Config(None, wx.ID_ANY, "")
    app.SetTopWindow(frame_1)
    frame_1.Show()
    app.MainLoop()
